# Generated by Django 5.0.6 on 2024-06-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.DeleteModel(
            name='classroom',
        ),
        migrations.DeleteModel(
            name='conversation',
        ),
    ]
