# Generated by Django 5.0.6 on 2024-06-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='room',
        ),
    ]
