# Generated by Django 5.0.6 on 2024-06-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
